remote_theme: riggraz/no-style-please
title: disquet.net # name of the site
author: Álvaro Martínez i Majado # name of site's author
email: a@alvaro.cat # email of site's author
url: https://disquet.ent # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Dispositiu d'emmagatzematge lo-fi per a enllaços d'interès (hi estigui d'acord o no)
favicon: "" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

paginate: 2
paginate_path: ./page:num/
  
theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%d-%m-%Y" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
